# Generated by Django 5.0.4 on 2024-04-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tumodelo',
            old_name='campo2',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='tumodelo',
            old_name='campo3',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='tumodelo',
            old_name='campo1',
            new_name='Nombre',
        ),
    ]
