# Generated by Django 5.0.4 on 2024-04-15 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='texto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='comentario.texto'),
            preserve_default=False,
        ),
    ]
